power: reset: Fix Axxia DDR Retention for kernel 5.10
commit 8dcfe80c187cb2a4834794368db1efb8e0a303ba from
https://github.com/axxia/linux-yocto.git v5.10/standard/axxia-dev/base.

drivers/power/reset/axxia-reset.c:109:18: error: passing argument 4
   of 'proc_create' from incompatible pointer type
   [-Werror=incompatible-pointer-types]

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: John Jacques <john.jacques@intel.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>